required = ["github.com/onsi/ginkgo/ginkgo", "github.com/maxbrunsfeld/counterfeiter"]

[[constraint]]
  revision = "c45b897f13350786ccaf2b7403b92b1c7ad85844"
  name = "github.com/BurntSushi/migration"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  revision = "2704adc878c21e1329f46f6e56a1c387d788ff94"
  name = "github.com/lib/pq"

# dep ensure issue in https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true
