---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: config-server
  path: config-server

run:
  path: config-server/ci/tasks/test-golangci-lint.sh
