// Code generated by counterfeiter. DO NOT EDIT.
package typesfakes

import (
	"sync"

	"github.com/cloudfoundry/config-server/types"
)

type FakeValueGeneratorFactory struct {
	GetGeneratorStub        func(valueType string) (types.ValueGenerator, error)
	getGeneratorMutex       sync.RWMutex
	getGeneratorArgsForCall []struct {
		valueType string
	}
	getGeneratorReturns struct {
		result1 types.ValueGenerator
		result2 error
	}
	getGeneratorReturnsOnCall map[int]struct {
		result1 types.ValueGenerator
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeValueGeneratorFactory) GetGenerator(valueType string) (types.ValueGenerator, error) {
	fake.getGeneratorMutex.Lock()
	ret, specificReturn := fake.getGeneratorReturnsOnCall[len(fake.getGeneratorArgsForCall)]
	fake.getGeneratorArgsForCall = append(fake.getGeneratorArgsForCall, struct {
		valueType string
	}{valueType})
	fake.recordInvocation("GetGenerator", []interface{}{valueType})
	fake.getGeneratorMutex.Unlock()
	if fake.GetGeneratorStub != nil {
		return fake.GetGeneratorStub(valueType)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getGeneratorReturns.result1, fake.getGeneratorReturns.result2
}

func (fake *FakeValueGeneratorFactory) GetGeneratorCallCount() int {
	fake.getGeneratorMutex.RLock()
	defer fake.getGeneratorMutex.RUnlock()
	return len(fake.getGeneratorArgsForCall)
}

func (fake *FakeValueGeneratorFactory) GetGeneratorArgsForCall(i int) string {
	fake.getGeneratorMutex.RLock()
	defer fake.getGeneratorMutex.RUnlock()
	return fake.getGeneratorArgsForCall[i].valueType
}

func (fake *FakeValueGeneratorFactory) GetGeneratorReturns(result1 types.ValueGenerator, result2 error) {
	fake.GetGeneratorStub = nil
	fake.getGeneratorReturns = struct {
		result1 types.ValueGenerator
		result2 error
	}{result1, result2}
}

func (fake *FakeValueGeneratorFactory) GetGeneratorReturnsOnCall(i int, result1 types.ValueGenerator, result2 error) {
	fake.GetGeneratorStub = nil
	if fake.getGeneratorReturnsOnCall == nil {
		fake.getGeneratorReturnsOnCall = make(map[int]struct {
			result1 types.ValueGenerator
			result2 error
		})
	}
	fake.getGeneratorReturnsOnCall[i] = struct {
		result1 types.ValueGenerator
		result2 error
	}{result1, result2}
}

func (fake *FakeValueGeneratorFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getGeneratorMutex.RLock()
	defer fake.getGeneratorMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeValueGeneratorFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ types.ValueGeneratorFactory = new(FakeValueGeneratorFactory)
