---
jobs:
  - name: test-golangci-lint
    public: true
    plan:
      - get: config-server
        trigger: true
      - task: test-golangci-lint
        file: config-server/ci/tasks/test-golangci-lint.yml

  - name: test-unit
    public: true
    plan:
      - get: config-server
        trigger: true
      - task: test-unit
        file: config-server/ci/tasks/test-unit.yml

  - name: test-integration-in-memory
    public: true
    plan:
      - get: integration-image
      - get: config-server
        trigger: true
      - task: test-integration
        image: integration-image
        privileged: true
        file: config-server/ci/tasks/test-integration.yml
        params:
          DB: memory

  - name: test-integration-mysql
    public: true
    plan:
      - get: main-mysql-8-0-image
      - get: config-server
        trigger: true
      - task: test-integration
        image: main-mysql-8-0-image
        privileged: true
        file: config-server/ci/tasks/test-integration.yml
        params:
          DB: mysql

  - name: test-integration-postgresql
    public: true
    plan:
      - get: config-server
        trigger: true
      - get: main-postgres-15-image
      - task: test-integration
        image: main-postgres-15-image
        privileged: true
        file: config-server/ci/tasks/test-integration.yml
        params:
          DB: postgresql
          DB_VERSION: 15

  - name: build
    public: true
    plan:
      - in_parallel:
        - get: config-server
          passed: [test-golangci-lint, test-unit, test-integration-in-memory, test-integration-mysql, test-integration-postgresql]
          trigger: true
        - get: version-semver
          params: {bump: patch}
      - {put: version-semver, params: {file: version-semver/number}}
      - in_parallel:
        - task: build-linux
          file: config-server/ci/tasks/build-linux.yml
        - task: build-darwin
          file: config-server/ci/tasks/build-darwin.yml
      - {put: config-server-promoted, params: {repository: config-server, tag: version-semver/number, tag_prefix: v}}

  - name: bump-minor
    public: true
    plan:
      - get: version-semver
        params: {bump: minor}
      - {put: version-semver, params: {file: version-semver/number}}

  - name: bump-major
    public: true
    plan:
      - get: version-semver
        params: {bump: major}
      - {put: version-semver, params: {file: version-semver/number}}

  - name: bump-deps
    plan:
    - in_parallel:
      - get: config-server
      - get: golang-release
      - get: weekly
        trigger: true
    - task: bump-deps
      file: golang-release/ci/tasks/shared/bump-deps.yml
      input_mapping:
        input_repo: config-server
      output_mapping:
        output_repo: bumped-config-server
    - task: test-unit
      file: config-server/ci/tasks/test-unit.yml
      input_mapping:
        config-server: bumped-config-server
    - put: config-server
      params:
        repository: bumped-config-server
        rebase: true

resources:
  - name: main-postgres-15-image
    type: docker-image
    source:
      repository: bosh/main-postgres-15
      tag: main

  - name: main-mysql-8-0-image
    type: docker-image
    source:
      repository: bosh/main-mysql-8.0
      tag: main
      username: ((docker.username))
      password: ((docker.password))

  - name: integration-image
    type: docker-image
    source:
      repository: bosh/integration
      tag: main

  - name: config-server
    type: git
    source:
      uri: https://github.com/cloudfoundry/config-server.git
      branch: develop
      username: bosh-admin-bot
      password: ((github_public_repo_token))

  - name: config-server-promoted
    type: git
    source:
      uri: https://github.com/cloudfoundry/config-server.git
      branch: master
      username: bosh-admin-bot
      password: ((github_public_repo_token))

  - name: golang-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-package-golang-release.git

  - name: version-semver
    type: semver
    source:
      initial_version: "0.1.216"
      driver: git
      uri: https://github.com/cloudfoundry/config-server.git
      branch: release-semver
      file: VERSION
      username: bosh-admin-bot
      password: ((github_public_repo_token))

  - name: weekly
    type: time
    source:
      start: 3:00 -0700
      stop: 4:30 -0700
      days: [ Saturday ]

resource_types:
- name: semver
  type: docker-image
  source:
    repository: concourse/semver-resource