name: go
on:
  push:
  pull_request:
jobs:
  lint:
    strategy:
      matrix:
        go: [1.19]
        os: [macos-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          args: --enable goimports
