name: go
on:
  push:
  pull_request:
jobs:
  lint:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v3
